#!/bin/bash

# best to run this in a git-worktree
# example runes in main tree:
#  git-branch -f pretest && git-branch -f tested `git-merge-base HEAD tested` && git-checkout wip

set -e
while true; do
    next=$(git-rev-list --reverse tested..pretest | head -n1)
    if [ "x$next" = x ]; then break; fi
    git checkout "$next"
    ./comprehensive-test
    git push . HEAD:tested
done
