#! /usr/bin/tclsh
# This file is part of secnet.
# See LICENCE and this file CREDITS for full list of copyright holders.
# SPDX-License-Identifier: GPL-3.0-or-later
# There is NO WARRANTY.

source mtest/common.tcl

run-mss --no-conf-key-prefix --pubkeys-elide test-example/sites $tmp/out.conf

diff-mss-sites-conf mtest/e-basic.conf $tmp/out.conf

