#! /usr/bin/tclsh
# This file is part of secnet.
# See LICENCE and this file CREDITS for full list of copyright holders.
# SPDX-License-Identifier: GPL-3.0-or-later
# There is NO WARRANTY.

source mtest/common.tcl

run-mss --filter --output-version=1 test-example/sites $tmp/out.sites

diff  mtest/e-filter.sites $tmp/out.sites $seddery
