#! /usr/bin/tclsh

source mtest/common.tcl

run-mss -Ppprefix --no-conf-key-prefix --pubkeys-elide test-example/sites $tmp/out.conf

diff  mtest/e-basic.conf $tmp/out.conf \
    "sed -e 's/vpn/pprefixvpn/g; s/^all-sites/pprefix&/' | $seddery" \
    $seddery
