#!/bin/bash
# subdirmk - toplevel invocation script for the test suite
#  Copyright 2019 Mark Wooding
#  Copyright 2019 Ian Jackson
# SPDX-License-Identifier: LGPL-2.0-or-later
# There is NO WARRANTY.

set -e

j=$(nproc 2>/dev/null || echo 1)
j=$(( $j * 5 / 4 + 1 ))

x () { echo "$@"; "$@"; }
x ${MAKE-make} -f tests/tests.mk -j$j
echo 'ok.'
