#!/bin/bash
set -e
set -o pipefail

cd tests/filter

expand <../../README | ./extract-doctest . >/dev/null

../../generate sub/dir
files=$(find -name \*.expected)
for f in $files; do
	i=$f
	o=$f.tmp
	sed <$i >$o '
		/^# doctests:/ {
			r '"${f%/*}/doctest.mk.part"'
			a
		}
	'
	diff -u $f.tmp ${f%.expected}.tmp
done

echo ok.
