#! /bin/sh
# /etc/init.d/secnet
#
# This file is part of secnet.
# See LICENCE and CREDITS for full list of copyright holders.
# SPDX-License-Identifier: GPL-3.0-or-later
# There is NO WARRANTY.

### BEGIN INIT INFO
# Provides:          secnet
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop secnet
# Description:       secnet is a VPN server.
### END INIT INFO

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/secnet
NAME=secnet
USER=
LOGFILE=/var/log/secnet
DESC="VPN server"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

test -f /etc/secnet/secnet.conf || exit 0
test -f /etc/default/secnet && . /etc/default/secnet

[ "X$RUN_SECNET" = "Xyes" ] || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --oknodo --pidfile \
	    /var/run/$NAME.pid --exec $DAEMON
	echo "$NAME."
	;;
  log-reopen)
        if [ "x$USER" != x ] && ! test -f /var/log/secnet; then (
	    echo "Recreating $DESC logfile $LOGFILE owned by $USER."
	    umask 027
	    touch -- "$LOGFILE"
	    chown $USER:adm "$LOGFILE"
	); fi

	echo "Causing $DESC to reopen its logfiles."
	start-stop-daemon --stop --signal 1 --quiet --oknodo 	\
	    --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON
  	;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
		--oknodo --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload|log-reopen}" >&2
	exit 1
	;;
esac

exit 0
