#!/bin/sh
set -ex

cd example

#----- in-tree build -----

git clean -xdff
./autogen.sh && ./configure
make -j4 all check
make -j4 clean
make -j4 all check

#----- out of tree build -----

git clean -xdff
mkdir build
cd build
>>../src/for-test.sd.mk
>>../lib/for-test.mk.in
.././autogen.sh && ../configure
make -j4 all check

#----- testing rebuild on input change -----

echo '# for-check 1' >>../src/for-test.sd.mk
make -j4
grep '^# for-check 1' src/Subdir.mk || false

echo '# for-check 2' >>../lib/for-test.mk.in
make -j4
grep '^# for-check 2' lib/for-test.mk || false

echo ok.
