#!/bin/sh
set -ex

. tests/build-common

cd example

: ----- in-tree build -----

git clean -xdff
./autogen.sh && ./configure
make -j4 all check
make -j4 clean
make -j4 all check

: ----- out of tree build -----

git clean -xdff
mkdir build
cd build
>>../src/for-test.sd.mk
>>../lib/for-test.mk.in
.././autogen.sh && ../configure
make -j4 all check

: ----- testing rebuild on input change -----

reset_times () {
	find -type f -print0 \
	| xargs -0 \
	touch -hmd 'now -1 seconds' --
}

: ----- for-check-1 -----
reset_times
echo 'for-check-1:' >>../src/for-test.sd.mk
make -j4 for-check-1
grep '^for-check-1:' src/Subdir.mk || false

: ----- for-check-2 -----
reset_times
echo 'for-check-2:' >>../lib/for-test.mk.in
make -j4 for-check-2
grep '^for-check-2:' lib/for-test.mk || false

echo ok.
