#! /usr/bin/tclsh
# This file is part of secnet.
# See LICENCE and this file CREDITS for full list of copyright holders.
# SPDX-License-Identifier: GPL-3.0-or-later
# There is NO WARRANTY.

set oldsecnet(inside) 1
set initiator outside
source stest/t-nonnego-on
