#! /usr/bin/tclsh
# This file is part of secnet.
# See LICENCE and this file CREDITS for full list of copyright holders.
# SPDX-License-Identifier: GPL-3.0-or-later
# There is NO WARRANTY.

source stest/common.tcl

# `non-negotiating' ends:
set privkey(inside) test-example/inside.key
# So old, new; ie -on

# There is no -no because the sites file tells a new inside to expect
# a different key.

test-kex
